### PR TITLE
Add macOS flashing instructions.

### PR DESCRIPTION
**Pull request by sjorge**

### CODE REVIEW

**Comment by omerk** [comment]
Great addition, thank you!

**Comment by omerk** [comment]
Hmm, looks like merge failed with "repository that submitted this pull request has been deleted" @sjorge?

**Comment by sjorge** [comment]
Oops my script to auto cleanup closed pr probably saw the close and assumed it was OK.

**Comment by sjorge** [comment]
Odd it still lists the .patch url for me:
https://github.com/electrolama/docs/commit/d2ea2d4fe36f2a81e94eb98106cf4616be26db6f.patch

**Comment by omerk** [comment]
Yeah I don't know quite what happened there, thanks for re-opening the PR!

**Pull request closed without merging**
